name: zestnews
description: A new Flutter application.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^0.1.3
  http: ^0.12.0+2
  cached_network_image: ^2.0.0
  webview_flutter: ^0.3.19+19
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
   - asset/images/
  #   - images/a_dot_ham.jpeg

#  assets:
#   -asset/images/breakingnews.jpg
#   -asset/images/business.jpg
#   -asset/images/education.jpg
#   -asset/images/entertainment.jpg
#   -asset/images/health.jpg
#   -asset/images/news.jpg
#   -asset/images/politics.jpg
#   -asset/images/sport.jpg